server:
  port: 8094
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://176.201.103.4:33006/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
    
  
#mybatis-plush配置
mybatis-plus:
    #别名包  简化类型转化的写法
  type-aliases-package: com.jt.pojo
    #加载mybatis的映射文件
  mapper-locations: classpath:/mybatis/mappers/*.xml
    #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
 
#dubbo配置项   
dubbo:
  scan:
    basePackages: com.jt  #配置包扫描
  application:            #服务名称必须定义
    name: provider-cart
  registry:               #注册中心
    address: zookeeper://176.201.103.23:2181?backup=176.201.103.23:2182,176.201.103.23:2183
  protocol:
    name: dubbo           #zookeeper节点名称
    port: 20881           #RPC通信 dubbo内部通信端口 
 
 
#引入日志
logging:
  level:
    com.jt.mapper: debug
      
  